config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root to: 'wfiles#index'
  resources :wfiles
  get 'ex', to: 'wfiles#ex'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/wfile.rb
class Wfile < ApplicationRecord
  has_many :children, class_name: 'Wfile',
                      foreign_key: 'parent_id'

  belongs_to :parent, class_name: 'Wfile', optional: true

  enum :type, %i[dir file]
  validates :name, presence: true

  def formatted_created_at
    created_at.strftime('%d.%m.%Y %H:%M:%S')
  end

  private

  def make_path
    if parent.nil?
      self.path = name.to_s
    else
      parent = Wfile.find(self.parent)
      self.path = "#{parent.path}/#{name}"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/sortabl.rb
module Sortabl
  extend ActiveSupport::Concern

  included do
    before_action :set_sort_params
  end

  def set_sorter
    unless @sort_param.empty?
      ap @sort_param
      ap session["#{@resource.to_s.underscore}_sort"]
      ap @sort_param.dig(:sort, :column) == session.dig("#{@resource.to_s.underscore}_sort", 'column')
      if @sort_param.dig(:sort, :column) == session.dig("#{@resource.to_s.underscore}_sort", 'column')
      direction = case session.dig("#{@resource.to_s.underscore}_sort", 'direction')
                  when nil
                    'asc'
                  when 'asc'
                    'desc'
                  when 'desc'
                    nil
                  end
      else
        direction = nil
      end
      ap direction
      ap @sort_param[:sort].merge({ direction: direction })
      session["#{@resource.to_s.underscore}_sort"] = @sort_param[:sort].merge({ direction: direction })
    end
    # ap "session.dig: #{session.dig("#{Wfile.to_s.underscore}_filters", 'column')}"
    #if column == session.dig("#{resource.to_s.underscore}_filters", 'column')
    #  puts session.dig("#{resource.to_s.underscore}_filters", 'direction')
    #  case session.dig("#{resource.to_s.underscore}_filters", 'direction')
    #  when nil
    #    'asc'
    #  when 'asc'
    #    'desc'
    #  end
    # end
    session["#{Wfile.to_s.underscore}_filters"] = params.permit(:column, :direction)
  end


  def set_sort_params
    @sort_param = params.permit(sort: {})
  end
end

app/controllers/wfiles_controller.rb
class WfilesController < ApplicationController
  include Sortabl

  before_action :set_resourse, only: %i[show destroy edit update]
  before_action :set_scope, only: :index

  def index
    @sort_params = params[:sort]
  end

  def new
    ap params[:parent]
    @resourse = Wfile.new
    @resourse.parent = Wfile.find(params[:parent])
    ap @resourse
  end

  def create
    ap params
    @resourse = Wfile.new files_params
    if @resourse.save
      flash[:success] = 'File created!'
      redirect_to wfiles_path
    else
      render :new
    end
  end

  def update
    if @resourse.update files_params
      flash[:success] = 'File updated!'
      redirect_to wfiles_path
    else
      render :edit
    end
  end

  def destroy
    @resourse.destroy
    flash[:success] = 'File deleted!'
    redirect_to wfiles_path
  end

  def show
    @content = @resourse.children
  end

  def ex
  end
 
  private

  def set_scope
    @files = Wfile.all
  end

  def files_params
    params.require(:wfile).permit(:item_name, :parent, :item_type)
  end

  def set_resourse
    @resourse = Wfile.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sort_helper.rb
module SortHelper
  def sort_link(label, column, params)
    link_to label, wfiles_path(sort: { column: column, direction: next_direction(column, params) }), class: 'sortable'
  end

  def sort_class(column, params)
    next_direction(column, params)
  end

  def next_direction(column, params)
    return '' if params.nil?
    return '' unless column == params['column']

    case params['direction']
    when ''
      'asc'
    when 'asc'
      'desc'
    when 'desc'
      ''
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebLib1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <header class="pg-3 bg-dark text-white">
      <div class="container">
        <nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center md-md-0">
            <li><%= link_to 'Home', wfiles_path, class:"nav-link px-2 text-white" %></li>
            <%= content_for?(:create_link) ? yield(:create_link) : '' %>
            <li><%= link_to 'Test page', ex_path, class:"nav-link px-2 text-white" %></li>
            <%= content_for?(:create_link) ? yield(:create_link) : '' %>
          </ul>
        </nav>
      </div>
    </header>
    <main class="container mt-3">
      <% flash.each do |k, v| %>
        <%= tag.div v, class: "alert alert-#{k}", role: 'alert' %>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/share/_errors.html.erb
<% if object.errors.full_messages.any? %>
  <div class='alert alert-danger'>
    <ul class='mb-0'>
      <% object.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %> 
    </ul>
  </div>
<% end %>

app/views/wfiles/_form.html.erb
<%= render 'share/errors', object: @resourse%>
<%= form_with model: @resourse, url: form_path, data: { turbo: false } do |f| %>
  <div class='mb-3 row'>
    <div class='col-sm-2 col-form-label'>
      <%= f.label :item_name %>
    </div>

    <div class='col-sm-10'>
      <%= f.text_field :item_name, placeholder: "Новый файл", class: 'form-control' %>
    </div>
  </div>

  <div class='mb-3 row'>
    <div class='col-sm-2 col-form-label'>
      <%= f.label :item_type %>
    </div>
    
  </div>
  <%= f.hidden_field :parent_id, value: @resourse.parent_id %>
  <%= f.submit "Создать", class: 'btn btn-primary'  %>

<% end %>

app/views/wfiles/edit.html.erb
<h1 class='mb-4'>Edit file</h1>

<%= render 'form', form_path: wfile_path(@resourse.item_path)%>

app/views/wfiles/ex.html.erb
<div class='pannel_container'>
  <div class='pannel'>
  </div>
  <div class='pannel'>
  </div>
  <div class='pannel'>
  </div>
</div>

app/views/wfiles/index.html.erb
<h1>Files</h1>

<table class='table table-bordered table-sortable'>
  <thead>
    <tr>
      <th class=<%= sort_class 'name', @sort_params %> > 
          <%= sort_link 'Item name', 'name', @sort_params %>
      </th>
      <th class=<%= sort_class 'type', @sort_params %> >
          <%= sort_link 'Item type', 'type', @sort_params %>
      </th>
      <th class=<%= sort_class 'created_at', @sort_params %> >
          <%= sort_link 'Item create time', 'created_at', @sort_params %>
      </th>
    </tr>
  </thead>
  <tbody>
  <% @files.each do |file| %>
    <tr>
      <td><%= link_to file.name, wfile_path(file) %></td>
      <td><%= file.is_dir %></td>
      <td>
        <time datetime=<%= file.formatted_created_at%>>
          <%= file.formatted_created_at %>
        </time>
      </td>
      <td>
        <%= link_to 'edit', edit_wfile_url(file) %>
        <%= link_to 'delete', wfile_path(file), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}  %>
      </td>
    </tr>
  <% end %>
</table>

app/views/wfiles/new.html.erb
<h1 class='mb-4'>New file</h1>

<%= render 'form', form_path: wfiles_path %>

app/views/wfiles/show.html.erb
<% content_for :create_link do %>
  <li><%= link_to 'New file', new_wfile_path(parent: @resourse.id), class:"nav-link px-2 text-white" %></li>
<% end %>

<h1><%= @resourse.name %></h1>

<table>
  <thead>
    <tr>
      <th>Item name</th>
      <th>Item type</th>
      <th>Item create time</th>
    </tr>
  </thead>
  <tbody>
  <% @content.each do |file| %>
    <tr>
      <td><%= file.name %></td>
      <td><%= file.type %></td>
      <td>
        <time datetime=<%= file.formatted_created_at%>>
          <%= file.formatted_created_at %>
        </time>
      </td>
      <td>
        <%= link_to 'edit', edit_wfile_path(file) %>
        <%= link_to 'delete', wfile_path(file), data: {"turbo-method": :delete, "turbo-confirm": 'Are you sure?'}  %>
      </td>
    </tr>
  <% end %>
</table>